version: "3.8"
services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5000"
    volumes:
      - ./Core:/app/Core
      - ./TestProject:/app/TestProject
      - ./InterfacesAia:/app/InterfacesAia
